### ISSUE TITLE
Mention the 'opportunistic repeat' as a solution for lossy links

### ISSUE THREAD

**Issue by NicoKos** [uoaerg/draft-jones-transport-for-satellite#11]
Such as proposed by Christian, there is a solution that could be interesting for SATCOM communications.
The idea behind opportunistic repeat is to retransmit packets even it they have not been detected as lost but transmitting packets is allowed by the congestion control.

**Comment by adventureloop** [comment]
I am going to rev this week, can you propose text for 02 after I have published?

**Comment by NicoKos** [comment]
Sure. I would be happy to do so.

**Comment by davidfdzp** [comment]
The transmission of packets two times just in case one is lost is used in some SATCOM and satellite navigation systems, where retransmission would be 'too late'. The 5G HARQ has a so called 'blind mode' for this and this is being considered in the 5G NTN (for SATCOM).

**Comment by NicoKos** [comment]
Should be solved by commit 28af8b589d650e266e67e6b55a48d8c32214e6a1
