### ISSUE TITLE
Changing the title of section "Mitigations Below the Transport Layer" 

### ISSUE THREAD

**Issue by NicoKos** [uoaerg/draft-jones-transport-for-satellite#4]
I think the title "Mitigations Below the Transport Layer" does not reflect the content of the section. 

I would propose "On-Path Mitigations" 

What do you think ?

**Comment by adventureloop** [comment]
I think there is something between these two. Wouldn't a split tcp pep also be an on path mitigation?

**Comment by adventureloop** [comment]
I think this is good, I will update the document
